# Generated by Django 5.1.4 on 2025-01-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'Admin'), (1, 'User'), (2, 'Publisher'), (3, 'Vip-user')], default=1, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'User'), (2, 'Publisher'), (3, 'Vip-user')], default=1),
        ),
    ]
