# Generated by Django 5.1.4 on 2025-01-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
